#ifndef _RODA_MESSAGE_KIND_H_
#define _RODA_MESSAGE_KIND_H_

#include <stdbool.h>

#include "text/string.h"

typedef enum {
    MESSAGE_UNKNOWN,
    MESSAGE_FATAL_ERROR,
    MESSAGE_ERROR,
    MESSAGE_WARNING,
    MESSAGE_NOTE,
    MESSAGE_HELP,
} MessageCategory;

#define NUM_MESSAGE_CATEGORY (MESSAGE_HELP + 1)

typedef enum {
    UNKNOWN_UNKNOWN,

    ERRORS_START,
    ERROR_UNKNOWN,
    ERROR_SYNTAX,
    ERROR_ALREADY_DEFINED,
    ERROR_UNDEFINED,
    ERROR_CANT_OPEN_FILE,
    ERROR_INVALID_STR,
    ERROR_INVALID_INT,
    ERROR_INVALID_REAL,
    ERROR_INCOMPATIBLE_TYPE,
    ERROR_NOT_CONSTEXPR,
    ERROR_INVALID_ARRAY_LENGTH,
    ERROR_UNINFERRED_TYPE,
    ERROR_INVALID_TYPE,
    ERROR_NO_OUTPUT_FILE,
    ERROR_NO_COMPILER_BACKEND,
    ERROR_LLVM_BACKEND_ERROR,
    ERROR_MISSING_RETURN,
    ERROR_LINKER,
    ERROR_UNSIZED_TYPE,
    ERROR_ARGUMENT_COUNT,
    ERROR_DUPLICATE_STRUCT_FIELD,
    ERROR_NO_SUCH_FIELD,
    ERROR_NO_SUCH_TARGET,
    ERRORS_END,

    WARNINGS_START,
    WARNING_UNKNOWN,
    WARNING_CMD_ARGS,
    WARNING_LLVM_BACKEND_WARNING,
    WARNINGS_END,
    
    NOTES_START,
    NOTE_UNKNOWN,
    NOTE_LLVM_BACKEND_REMARK,
    NOTE_LLVM_BACKEND_NOTE,
    NOTES_END,
    
    HELPS_START,
    HELP_UNKNOWN,
    HELPS_END,
} MessageKind;

#define NUM_MESSAGE_KIND (HELPS_END + 1)

ConstString getMessageKindString(MessageKind kind);

ConstString getMessageCategoryName(MessageCategory category);

MessageCategory getMessageCategoryFromName(ConstString category);

MessageCategory getMessageCategory(MessageKind kind);

#endif
